# Generated by Django 3.2.8 on 2021-10-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20211030_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='currentBid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
