# Generated by Django 3.2.8 on 2021-10-31 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_items_currentbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='currentBid',
        ),
        migrations.AddField(
            model_name='items',
            name='currentBider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_bider', to=settings.AUTH_USER_MODEL),
        ),
    ]
